ALTER TABLE "administradores"
  ADD COLUMN IF NOT EXISTS "documento" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "nascimento" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "faturamento_mensal" DECIMAL(12, 2),
  ADD COLUMN IF NOT EXISTS "cep" VARCHAR(12),
  ADD COLUMN IF NOT EXISTS "endereco" VARCHAR(180),
  ADD COLUMN IF NOT EXISTS "endereco_numero" VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "bairro" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "complemento" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tipo_empresa" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "termos_uso_aceito_em" TIMESTAMP(3);
